services:
  db:
    image: postgres:17
    volumes:
      - lastnight-db:/var/lib/postgresql/data
    env_file:
      - .env.pg
    ports:
      - "5432:5432"

  minio:
    image: minio/minio:RELEASE.2025-06-13T11-33-47Z
    env_file:
      - .env.minio
    volumes:
      - lastnight-minio:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --address ":9000" --console-address ":9001"

  redis:
    image: redis:7.2-alpine
    env_file:
      - .env.redis
    volumes:
      - lastnight-redis:/data
    ports:
      - "6379:6379"

  pgadmin:
    image: dpage/pgadmin4:8.4
    env_file:
      - .env.pgadmin
    volumes:
      - lastnight-pgadmin:/var/lib/pgadmin
    ports:
      - "4001:80"
    depends_on:
      - db

volumes:
  lastnight-db:
  lastnight-pgadmin:
  lastnight-minio:
  lastnight-redis:
